**Program1**

In [2]:
# Import necessary libraries
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the Iris dataset
iris = load_iris()
X = iris.data   # Features
y = iris.target # Labels

# Split dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Gaussian Naive Bayes classifier
model = GaussianNB()

# Train the model
model.fit(X_train, y_train)

# Predict using the test data
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

# Display results
print("=== Naïve Bayes Classifier on Iris Dataset ===")
print(f"Accuracy: {accuracy * 100:.2f}%")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(report)


=== Naïve Bayes Classifier on Iris Dataset ===
Accuracy: 100.00%

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



**program2**

In [3]:
# Program to implement Naïve Bayes Algorithm using private dataset and find the accuracy of the algorithm

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Load your private dataset
df = pd.read_csv("private_dataset.csv")  # Updated path to local CSV

# Preprocess data
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Naïve Bayes model
model = GaussianNB()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
print("private_dataset.csv =")
print(df)



Accuracy: 96.67%
private_dataset.csv =
     feature1  feature2  feature3     target
0         5.1       3.5       1.4     setosa
1         4.9       3.0       1.4     setosa
2         4.7       3.2       1.3     setosa
3         4.6       3.1       1.5     setosa
4         5.0       3.6       1.4     setosa
..        ...       ...       ...        ...
145       6.7       3.0       5.2  virginica
146       6.3       2.5       5.0  virginica
147       6.5       3.0       5.2  virginica
148       6.2       3.4       5.4  virginica
149       5.9       3.0       5.1  virginica

[150 rows x 4 columns]
