**program 1**

In [2]:
import numpy as np

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

print("Matrix A:\n",A)
print("Matrix B:\n",B)

#Addition
C=A+B
print("Addition of A and B:\n",C)

#Subtraction
D=A-B
print("Subtraction of A and B:\n",D)

#Multiplication
E=A*B
print("Element-wise multiplication of A and B:\n",E)

#Matrix multiplication
F=np.dot(A,B)
print("Matrix multiplication of A and B:\n",F)

#Transpose
G=A.T
print("Transpose of A:\n",G)






Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Addition of A and B:
 [[ 6  8]
 [10 12]]
Subtraction of A and B:
 [[-4 -4]
 [-4 -4]]
Element-wise multiplication of A and B:
 [[ 5 12]
 [21 32]]
Matrix multiplication of A and B:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
