**program 1**

In [ ]:
#program to demonstrate basic matrix operations using NumPy

import numpy as np

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

print("Matrix A:\n",A)
print("Matrix B:\n",B)

#Addition
C=A+B
print("Addition of A and B:\n",C)

#Subtraction
D=A-B
print("Subtraction of A and B:\n",D)

#Multiplication
E=A*B
print("Element-wise multiplication of A and B:\n",E)

#Matrix multiplication
F=np.dot(A,B)
print("Matrix multiplication of A and B:\n",F)

#Transpose
G=A.T
print("Transpose of A:\n",G)






Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Addition of A and B:
 [[ 6  8]
 [10 12]]
Subtraction of A and B:
 [[-4 -4]
 [-4 -4]]
Element-wise multiplication of A and B:
 [[ 5 12]
 [21 32]]
Matrix multiplication of A and B:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


**program2**

In [1]:
#program to demonstrate left singular matrix, summation of diagonal elements and right singular matrix using NumPy with SVD

import numpy as np

# Define a matrix
X =np.array([[1,2,3],[4,5,6],[7,8,9]])

#perform SVD (Singular Value Decomposition)
U, S, VT = np.linalg.svd(X)

print("Left Singular Matrix (U):\n", U)
print("Right Singular Matrix (VT):\n", VT)
print("Diagonal Elements of S:\n", S)

#choose the number of components to keep(eg.,2)
n_components = 2

# Reconstruct matrix with reduced dimensions
X_reconstructed = np.dot(U[:, :n_components], np.dot(np.diag(S[:n_components]), VT[:n_components, :]))

print("original matrix:\n", X)
print("\nReconstructed matrix with reduced dimensions:\n", X_reconstructed)



Left Singular Matrix (U):
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Right Singular Matrix (VT):
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
Diagonal Elements of S:
 [1.68481034e+01 1.06836951e+00 3.33475287e-16]
original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed matrix with reduced dimensions:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
